env:
  CODECLIMATE_REPO_TOKEN: 5ba0fafe4174fbd93d8e91e7decf4f8c3b5eb4ade63f5d136d9733481324eac3
language: node_js
node_js:
  - "7.8.0"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - "npm install"
script:
  - npm test
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build
after_success:
  - npm run coveralls
